In [1]:
import numpy as np

In [2]:
a = np.array([[1, 6],
             [2, 8],
             [3, 11],
             [3, 10],
             [1, 7]])

In [3]:
a


array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [4]:
a.size

10

In [5]:
a.shape

(5, 2)

столбец - признак, строка - наблюдение

### Среднее значение по каждому признаку (mean)

In [6]:
a.mean(axis=0)

array([2. , 8.4])

In [7]:
mean_a = np.array(a.mean(axis=0))

In [8]:
mean_a

array([2. , 8.4])

# Задание 2

### Массив a_centered - значение массива a минус средние значения признаков

In [9]:
a - mean_a

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [10]:
a_centered = a - mean_a

In [11]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [12]:
a_centered.shape

(5, 2)

In [56]:
a_1 = a_centered[:, 0]

In [57]:
a_2 = a_centered[:, 1]

In [59]:
a_1

array([-1.,  0.,  1.,  1., -1.])

In [58]:
a_2

array([-2.4, -0.4,  2.6,  1.6, -1.4])

In [60]:
a_centered_sp = np.dot(a_1, a_2)

In [61]:
a_centered_sp

8.0

### N - число наблюдений a_centered_sp/N-1


In [64]:
N=a.shape[0]

In [65]:
N

5

In [62]:
a_centered_sp / 4

2.0

# Задание 4*

In [67]:
np.cov(a.T)

array([[1. , 2. ],
       [2. , 4.3]])

In [68]:
np.cov(a.T)[0, 1]

2.0

In [69]:
a_centered_sp / 4 ==np.cov(a.T)[0, 1]

True

### Результат верный